apiVersion: v2
name: pagopa-gpd-rtp
description: Microservice that handles the forwarding of the debt positions to RTP
type: application
version: 0.59.0
appVersion: 0.7.3-1-PIDM-1478
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-gpd-rtp
  - name: cron-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-cache-cron
