apiVersion: v2
name: pagopa-gpd-rtp
description: Microservice that handles the forwarding of the debt positions to RTP
type: application
version: 0.52.0
appVersion: 0.7.0-3-fix-taxonomy
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
  - name: cron-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-cache-cron
